title: Environmental History @ Harvard
# Short bio or description (displayed in the header)
description: Chronicling the Harvard History Department's Environmental History Curricular Initiative
theme: just-the-docs
